name: Test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - uses: aloucks/vulkan-ci@master

    - run: cargo test --manifest-path=test/Cargo.toml -- --nocapture
      env:
        VK_LOADER_DEBUG: all